---
services:
  db:
    image: mysql:8.0
    environment: # Sets environment variables for the database configuration
      - MYSQL_DATABASE=appdb # Specifies the name of the database
      - MYSQL_PASSWORD=pass123 # Sets the password for the MySQL user
      - MYSQL_ROOT_PASSWORD=pass123 # Sets the root password for MySQL
    networks:
      - db # Connects the service to the 'sameNetworkAsMysql' network
    ports:
      - 3307:3306 # Maps the container's port 3306 to the host's port 3307
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  backend:
    #container_name: infnet_backend
    build: # Builds the backend API using the provided Dockerfile
      context: ./backend # Specifies the build context directory for the backend
      dockerfile: Dockerfile # Specifies the Dockerfile to use for building the backend
    image: ${DOCKERHUB_USERNAME}/infnet_backend:latest
    ports:
      - 3000:3000 # Maps the container's port 3000 to the host's port 3000
    networks:
      - db # Connects the service to the 'sameNetworkAsMysql' network
    depends_on:
      - db # Specifies that the 'api' service depends on the 'db' service

  frontend:
    #container_name: infnet_frontend
    restart: on-failure # Restarts the container if it fails
    build: # Builds the frontend app using the provided Dockerfile
      context: ./frontend # Specifies the build context directory for the frontend
    image: ${DOCKERHUB_USERNAME}/infnet_frontend:latest
    ports:
      - 3001:3000 # Maps the container's port 3000 to the host's port 3001
    networks:
      - db # Connects the service to the 'sameNetworkAsMysql' network
    depends_on:
      - backend # Specifies that the 'frontend' service depends on the 'api' service

networks:
  db: # Defines the 'sameNetworkAsMysql' network
    driver: bridge # Specifies the network driver as 'bridge'
